name: CI
on:
  push:
    branches:
      - main
    tags: "*"

jobs:
  latex:
    name: "Fontist - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0.0"
      - uses: fontist/setup-fontist@v2
        if: matrix.os == 'windows-latest'
      - run: fontist install --formula "DejaVu"
        if: matrix.os == 'windows-latest'
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-medium
            hyperref
            minted
            svg
            newunicodechar
            transparent
            upquote
      - run: latexmk -f UncertaintyQuantification.jl.tex
