name: CI
on:
  push:
    branches:
      - main
    tags: "*"

jobs:
  latex:
    name: "Fontist - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Download and install DejaVu Fonts"
        run: |
          Invoke-WebRequest "https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip" -OutFile "DejaVu.zip"
          Expand-Archive -Path "DejaVu.zip" -DestinationPath "."
          $fonts = (New-Object -ComObject Shell.Application).Namespace(0x14)
          foreach ($file in gci -Path ".\dejavu-fonts-ttf-2.37\ttf" "*.ttf")
          {
            $fonts.CopyHere($file.fullname)
          }
        if: matrix.os == 'windows-latest'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        if: matrix.os == 'windows-latest'
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-medium
            hyperref
            minted
            newunicodechar
            transparent
            upquote
            tabulary
            tcolorbox
      - run: latexminted --version
      - run: latexmk -f UncertaintyQuantification.jl.tex
      - uses: actions/upload-artifact@v4
        with:
          path: "UncertaintyQuantification.jl.pdf"
